import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, Settings } from 'lucide-react'

import { createBookmakerConstraint, createTaxProfile, loadArbitrageSettings } from '../api/client'
import { formatDateTime } from '../lib/format'
import type { ArbitrageSettings as SettingsData } from '../types'

export function ArbitrageSettings() {
  const [settings, setSettings] = useState<SettingsData | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { try { setSettings(await loadArbitrageSettings()); setError(null) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load settings') } finally { setLoading(false) } }, [])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  return <section className="border border-zinc-200 bg-white"><div className="border-b border-zinc-200 p-5"><div className="flex items-center gap-2"><Settings aria-hidden="true" size={18} /><h2 className="font-bold">Tax and stake evidence</h2></div><p className="mt-1 text-sm text-zinc-500">Record sourced, timestamped bookmaker terms. Unknown or stale evidence still blocks executable status.</p></div>{loading ? <p className="p-5 text-sm text-zinc-500">Loading bookmaker settings…</p> : error ? <p className="m-5 border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900">{error}</p> : settings ? <SettingsWorkspace settings={settings} onSaved={load} /> : null}</section>
}

export function SettingsWorkspace({ settings, onSaved }: { settings: SettingsData; onSaved: () => Promise<void> }) {
  const [mode, setMode] = useState<'tax' | 'constraint'>('tax'); const [bookmakerId, setBookmakerId] = useState(String(settings.bookmakers[0]?.id ?? '')); const [currency, setCurrency] = useState('EUR'); const [source, setSource] = useState(''); const [timestamp, setTimestamp] = useState(''); const [adminKey, setAdminKey] = useState(''); const [jurisdiction, setJurisdiction] = useState(''); const [stakeTax, setStakeTax] = useState('0'); const [winningsTax, setWinningsTax] = useState('0'); const [withholding, setWithholding] = useState('0'); const [commission, setCommission] = useState('0'); const [fixedFee, setFixedFee] = useState('0'); const [minimum, setMinimum] = useState('0'); const [maximum, setMaximum] = useState(''); const [increment, setIncrement] = useState('0.01'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const submit = async () => { setBusy(true); setError(null); setMessage(null); try { if (mode === 'tax') { await createTaxProfile({ bookmaker_id: Number(bookmakerId), name: `${jurisdiction} bookmaker terms`, jurisdiction, currency, tax_basis: 'per_bet', stake_tax_rate: pct(stakeTax), winnings_tax_rate: pct(winningsTax), payout_withholding_rate: pct(withholding), commission_rate: pct(commission), fixed_fee: Number(fixedFee), effective_from: iso(timestamp), verified_at: iso(timestamp), source_label: source }, adminKey || undefined) } else { await createBookmakerConstraint({ bookmaker_id: Number(bookmakerId), currency, minimum_stake: Number(minimum), ...(maximum ? { maximum_stake: Number(maximum) } : {}), stake_increment: Number(increment), observed_at: iso(timestamp), source_label: source }, adminKey || undefined) }; setMessage(`${mode === 'tax' ? 'Tax profile' : 'Stake constraint'} stored with provenance.`); await onSaved() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save settings') } finally { setBusy(false) } }
  const ready = Boolean(bookmakerId && source && timestamp && (mode === 'constraint' || jurisdiction))
  return <div><div className="flex border-b border-zinc-200"><button className={`px-5 py-3 text-sm font-bold ${mode === 'tax' ? 'bg-zinc-900 text-white' : ''}`} onClick={() => setMode('tax')} type="button">Tax profile</button><button className={`px-5 py-3 text-sm font-bold ${mode === 'constraint' ? 'bg-zinc-900 text-white' : ''}`} onClick={() => setMode('constraint')} type="button">Stake constraints</button></div><div className="p-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Select label="Bookmaker" value={bookmakerId} onChange={setBookmakerId} options={settings.bookmakers.map((item) => [String(item.id), `${item.name}${item.is_demo ? ' (demo)' : ''}`])} /><Input label="Currency" value={currency} onChange={(value) => setCurrency(value.toUpperCase())} /><Input label={mode === 'tax' ? 'Verified/effective at' : 'Observed at'} value={timestamp} onChange={setTimestamp} type="datetime-local" /><Input label="Source label" value={source} onChange={setSource} />{mode === 'tax' ? <><Input label="Jurisdiction" value={jurisdiction} onChange={setJurisdiction} /><Input label="Stake tax (%)" value={stakeTax} onChange={setStakeTax} type="number" /><Input label="Winnings tax (%)" value={winningsTax} onChange={setWinningsTax} type="number" /><Input label="Payout withholding (%)" value={withholding} onChange={setWithholding} type="number" /><Input label="Commission (%)" value={commission} onChange={setCommission} type="number" /><Input label="Fixed fee" value={fixedFee} onChange={setFixedFee} type="number" /></> : <><Input label="Minimum stake" value={minimum} onChange={setMinimum} type="number" /><Input label="Maximum stake" value={maximum} onChange={setMaximum} type="number" /><Input label="Stake increment" value={increment} onChange={setIncrement} type="number" /></>}<Input label="Admin key (memory only)" value={adminKey} onChange={setAdminKey} type="password" /></div><button className="mt-5 rounded-[5px] bg-zinc-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-40" disabled={!ready || busy} onClick={() => void submit()} type="button">{busy ? 'Saving…' : 'Store sourced evidence'}</button>{message ? <p className="mt-4 flex gap-2 border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><CheckCircle2 aria-hidden="true" size={18} />{message}</p> : null}{error ? <p className="mt-4 flex gap-2 border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900"><AlertTriangle aria-hidden="true" size={18} />{error}</p> : null}</div><EvidenceTable settings={settings} /></div>
}

function EvidenceTable({ settings }: { settings: SettingsData }) { return <div className="grid gap-5 border-t border-zinc-200 p-5 xl:grid-cols-2"><div><h3 className="mb-2 text-sm font-bold">Latest tax profiles</h3>{settings.tax_profiles.length ? settings.tax_profiles.slice(0, 8).map((item) => <div key={item.id} className="border-t border-zinc-100 py-3 text-xs"><p className="font-semibold">{item.bookmaker} · {item.jurisdiction} · {item.currency}</p><p className="mt-1 text-zinc-500">Stake {displayPct(item.stake_tax_rate)} · winnings {displayPct(item.winnings_tax_rate)} · commission {displayPct(item.commission_rate)}</p><p className="mt-1 text-zinc-400">Verified {formatDateTime(item.verified_at)} · {item.source_label}</p></div>) : <p className="text-sm text-amber-700">No sourced tax profiles.</p>}</div><div><h3 className="mb-2 text-sm font-bold">Latest stake constraints</h3>{settings.constraints.length ? settings.constraints.slice(0, 8).map((item) => <div key={item.id} className="border-t border-zinc-100 py-3 text-xs"><p className="font-semibold">{item.bookmaker} · {item.currency}</p><p className="mt-1 text-zinc-500">Min {item.minimum_stake} · max {item.maximum_stake ?? 'unknown'} · increment {item.stake_increment}</p><p className="mt-1 text-zinc-400">Observed {formatDateTime(item.observed_at)} · {item.source_label}</p></div>) : <p className="text-sm text-amber-700">No sourced stake constraints.</p>}</div></div> }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label><span className="mb-1 block text-xs font-semibold uppercase text-zinc-500">{label}</span><select aria-label={label} className="h-10 w-full border border-zinc-300 bg-white px-3 text-sm" value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label> }
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label><span className="mb-1 block text-xs font-semibold uppercase text-zinc-500">{label}</span><input aria-label={label} autoComplete="off" className="h-10 w-full border border-zinc-300 px-3 text-sm" step="any" type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label> }
function pct(value: string): number { return Number(value) / 100 }
function displayPct(value: string): string { return `${(Number(value) * 100).toFixed(2)}%` }
function iso(value: string): string { return new Date(value).toISOString() }
