import { useState } from 'react'
import { AlertTriangle, CheckCircle2, Database, Upload } from 'lucide-react'

import { uploadCsv } from '../api/client'
import { formatDateTime, humanizeCode } from '../lib/format'
import type { DashboardData, ImportUploadResult } from '../types'
import { IntelligenceBundleImport } from './IntelligenceBundleImport'

type UploadKind = 'odds' | 'results' | 'availability'

export function DataOperations({ dashboard }: { dashboard: DashboardData }) {
  const [adminKey, setAdminKey] = useState('')
  return <div className="space-y-8">
    <div><p className="text-xs font-bold uppercase text-emerald-700">Atomic ingestion</p><h2 className="mt-1 text-lg font-bold">Data operations</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-zinc-500">Upload complete timestamped CSV feeds. Any identity, completeness, chronology, settlement, or publication-time failure rejects the entire file.</p></div>
    <section className="border border-zinc-200 bg-white p-5"><label className="block max-w-md"><span className="mb-1.5 block text-xs font-semibold uppercase text-zinc-500">Admin key (memory only)</span><input aria-label="Import admin key" autoComplete="off" className="h-10 w-full border border-zinc-300 px-3 text-sm" type="password" value={adminKey} onChange={(event) => setAdminKey(event.target.value)} /></label><p className="mt-2 text-xs text-zinc-500">Sent only with upload requests and never persisted. Local development may leave it blank.</p></section>
    <section className="grid gap-5 xl:grid-cols-3"><ImportPanel adminKey={adminKey} kind="odds" title="Odds snapshots" detail="Complete coherent bookmaker markets with event, settlement, price, and observed-at identity." /><ImportPanel adminKey={adminKey} kind="results" title="Historical results" detail="Final scores observed no earlier than settlement; later corrections append rather than overwrite." /><ImportPanel adminKey={adminKey} kind="availability" title="Player availability" detail="Timestamped availability evidence with original publication and observation times." /></section>
    <IntelligenceBundleImport adminKey={adminKey} />
    <section><Heading eyebrow="Sources" title="Provider status" />{dashboard.providers.length ? <div className="overflow-x-auto border-y border-zinc-200 bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase text-zinc-500"><tr><th className="px-4 py-3">Provider</th><th className="px-4 py-3">Kind</th><th className="px-4 py-3 text-right">Events</th><th className="px-4 py-3 text-right">Snapshots</th><th className="px-4 py-3">Classification</th></tr></thead><tbody>{dashboard.providers.map((provider) => <tr key={provider.id} className="border-t border-zinc-100"><td className="px-4 py-3"><p className="font-semibold">{provider.name}</p><p className="text-xs text-zinc-500">{provider.slug}</p></td><td className="px-4 py-3">{humanizeCode(provider.kind)}</td><td className="px-4 py-3 text-right font-mono">{provider.event_count}</td><td className="px-4 py-3 text-right font-mono">{provider.snapshot_count}</td><td className="px-4 py-3"><Badge status={provider.is_demo ? 'demo' : 'external'} /></td></tr>)}</tbody></table></div> : <Empty text="No providers registered." />}</section>
    <section className="grid gap-7 xl:grid-cols-2"><div><Heading eyebrow="Ingestion" title="Recent import jobs" />{dashboard.imports.length ? <div className="border-y border-zinc-200 bg-white">{dashboard.imports.map((job) => <details key={job.id} className="border-b border-zinc-100 px-4 py-3 last:border-0"><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">#{job.id} · {job.filename}</p><p className="mt-1 text-xs text-zinc-500">{job.rows_imported}/{job.rows_received} rows · {formatDateTime(job.created_at)}</p></div><Badge status={job.status} /></div></summary>{job.errors.length ? <div className="mt-3 border-t border-zinc-100 pt-3"><p className="mb-2 text-xs font-bold uppercase text-rose-700">Rejection details</p>{job.errors.map((error, index) => <pre key={index} className="mt-2 overflow-x-auto whitespace-pre-wrap bg-rose-50 p-3 text-xs text-rose-900">{JSON.stringify(error, null, 2)}</pre>)}</div> : <p className="mt-3 border-t border-zinc-100 pt-3 text-xs text-zinc-500">No row errors recorded.</p>}</details>)}</div> : <Empty text="No import jobs recorded." />}</div><div><Heading eyebrow="Scheduler" title="Provider jobs" />{dashboard.jobs.length ? <div className="border-y border-zinc-200 bg-white">{dashboard.jobs.map((job) => <div key={job.id} className="flex items-start justify-between gap-3 border-b border-zinc-100 px-4 py-3 last:border-0"><div><p className="text-sm font-semibold">{job.provider} · {humanizeCode(job.job_type)}</p><p className="mt-1 text-xs text-zinc-500">{job.message || 'No provider message'} · {formatDateTime(job.created_at)}</p>{job.finished_at ? <p className="mt-1 text-xs text-zinc-400">Finished {formatDateTime(job.finished_at)}</p> : null}</div><Badge status={job.status} /></div>)}</div> : <Empty text="No provider jobs recorded." />}</div></section>
    <div className="flex gap-3 border-l-4 border-sky-500 bg-sky-50 px-4 py-3 text-sm leading-6 text-sky-950"><Database aria-hidden="true" className="mt-0.5 shrink-0" size={18} />Uploads are research ingestion only. Production requires the configured administrative key and provider terms must permit the submitted data.</div>
  </div>
}

function ImportPanel({ adminKey, kind, title, detail }: { adminKey: string; kind: UploadKind; title: string; detail: string }) {
  const [file, setFile] = useState<File | null>(null); const [sourceKey, setSourceKey] = useState(''); const [providerSlug, setProviderSlug] = useState(''); const [providerName, setProviderName] = useState(''); const [result, setResult] = useState<ImportUploadResult | null>(null); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false)
  const submit = async () => { if (!file) return; setSubmitting(true); setError(null); setResult(null); try { setResult(await uploadCsv(kind, file, { adminKey: adminKey || undefined, sourceKey, providerSlug, providerName })) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Upload failed') } finally { setSubmitting(false) } }
  const availabilityReady = kind !== 'availability' || Boolean(sourceKey && providerSlug && providerName)
  return <article className="border border-zinc-200 bg-white p-5"><Upload aria-hidden="true" className="text-emerald-700" size={22} /><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 min-h-16 text-sm leading-6 text-zinc-500">{detail}</p><label className="mt-4 block"><span className="mb-1.5 block text-xs font-semibold uppercase text-zinc-500">CSV file</span><input accept=".csv,text/csv" aria-label={`${title} CSV file`} className="block w-full text-xs" type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label>{kind === 'availability' ? <div className="mt-4 grid gap-3"><TextInput label="Source key" value={sourceKey} onChange={setSourceKey} /><TextInput label="Provider slug" value={providerSlug} onChange={setProviderSlug} /><TextInput label="Provider name" value={providerName} onChange={setProviderName} /></div> : null}<button className="mt-5 rounded-[5px] bg-zinc-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-40" disabled={!file || !availabilityReady || submitting} onClick={() => void submit()} type="button">{submitting ? 'Uploading…' : `Import ${kind}`}</button>{result ? <div className="mt-4 flex gap-2 border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900" role="status"><CheckCircle2 aria-hidden="true" className="shrink-0" size={18} /><div><p className="font-bold">Job #{result.job_id} {result.status}</p><p className="text-xs">{result.rows_imported}/{result.rows_received} rows imported atomically.</p></div></div> : null}{error ? <div className="mt-4 flex gap-2 border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900" role="alert"><AlertTriangle aria-hidden="true" className="shrink-0" size={18} /><span>{error}</span></div> : null}</article>
}

function TextInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span className="mb-1 block text-xs font-semibold uppercase text-zinc-500">{label}</span><input aria-label={label} className="h-9 w-full border border-zinc-300 px-3 text-sm" value={value} onChange={(event) => onChange(event.target.value)} /></label> }
function Heading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-3"><p className="text-xs font-bold uppercase text-emerald-700">{eyebrow}</p><h3 className="mt-1 text-lg font-bold">{title}</h3></div> }
function Badge({ status }: { status: string }) { const good = ['completed', 'external'].includes(status); const bad = ['failed', 'rejected'].includes(status); return <span className={`rounded-[4px] border px-2 py-1 text-xs font-bold ${good ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : bad ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-amber-200 bg-amber-50 text-amber-800'}`}>{status.toUpperCase()}</span> }
function Empty({ text }: { text: string }) { return <div className="border-y border-zinc-200 bg-white px-4 py-8 text-center text-sm text-zinc-500">{text}</div> }
