import { formatDateTime } from '../lib/format'
import type { MatchdayBookmakerCode, MatchdayCompetition, MatchdayEvent } from '../types'

export type BookmakerMode = 'both' | MatchdayBookmakerCode

export function BookmakerSettings({ mode, onChange }: { mode: BookmakerMode; onChange: (mode: BookmakerMode) => void }) {
  const choices: { value: BookmakerMode; label: string }[] = [{ value: 'both', label: 'Both apps' }, { value: 'allwyn', label: 'Allwyn' }, { value: 'novibet', label: 'Novibet' }]
  return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-200 bg-zinc-50 px-5 py-3"><div><p className="text-xs font-bold uppercase text-zinc-700">Suggestion platforms</p><p className="mt-0.5 text-xs text-zinc-500">Only exact stored prices from selected apps can qualify.</p></div><div aria-label="Suggestion platforms" className="flex" role="group">{choices.map((choice) => <button aria-pressed={mode === choice.value} className={`border px-3 py-2 text-xs font-bold first:rounded-l last:rounded-r ${mode === choice.value ? 'border-emerald-700 bg-emerald-700 text-white' : 'border-zinc-300 bg-white text-zinc-600 hover:bg-zinc-100'}`} key={choice.value} onClick={() => onChange(choice.value)} type="button">{choice.label}</button>)}</div></div>
}

export function CompetitionCard({ competition, selectedEventId, onSelect }: { competition: MatchdayCompetition; selectedEventId: number | null; onSelect: (eventId: number) => void }) {
  return <section className="overflow-hidden border border-zinc-200 bg-white"><div className="flex items-start justify-between gap-3 border-b border-zinc-200 bg-zinc-50 px-4 py-3"><div><p className="text-xs font-bold uppercase text-emerald-700">{competition.group_label}</p><h3 className="mt-0.5 font-bold">{competition.name}</h3></div><span className="text-xs text-zinc-500">{competition.country}</span></div>{competition.events.map((item) => <FixtureButton active={selectedEventId === item.event.id} item={item} key={item.event.id} onSelect={onSelect} />)}</section>
}

function FixtureButton({ item, active, onSelect }: { item: MatchdayEvent; active: boolean; onSelect: (eventId: number) => void }) {
  return <button className={`grid w-full grid-cols-[54px_1fr] gap-3 border-b border-zinc-100 px-4 py-4 text-left last:border-0 ${active ? 'bg-emerald-50' : 'hover:bg-zinc-50'}`} onClick={() => onSelect(item.event.id)} type="button"><div className="pt-0.5 text-center"><p className="font-mono text-sm font-bold">{kickoffTime(item.event.kickoff_at)}</p><p className="mt-1 text-[10px] font-bold uppercase text-zinc-400">{item.event.status}</p></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.event.home_team}</p><p className="mt-1 truncate text-sm font-semibold">{item.event.away_team}</p><div className="mt-2 flex flex-wrap gap-1.5 text-[10px] font-semibold uppercase"><span className={item.market_count ? 'text-zinc-600' : 'text-amber-700'}>{item.market_count ? `${item.market_count} markets` : 'Prices blocked'}</span><span className="text-zinc-300">·</span><span className={item.bookmaker_count ? 'text-zinc-600' : 'text-amber-700'}>{item.bookmaker_count ? `${item.bookmaker_count} books` : 'No books'}</span><span className="text-zinc-300">·</span>{item.latest_prediction_at ? <span className="text-sky-700" title={`Latest cutoff-safe prediction ${formatDateTime(item.latest_prediction_at)}`}>Model ready</span> : <span className="text-amber-700" title="No cutoff-safe prediction is stored. Open the match to inspect team-history and model evidence.">Model blocked</span>}<span className="text-zinc-300">·</span>{item.qualified_signal_count ? <span className="text-emerald-700">{item.qualified_signal_count} value</span> : <span className="text-zinc-400">No qualified value</span>}</div></div></button>
}

function kickoffTime(value: string): string { return new Intl.DateTimeFormat(undefined, { hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
