"""initial point in time schema

Revision ID: 60f015680124
Revises:
Create Date: 2026-07-19 14:11:43.340055

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60f015680124"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmakers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("rows_received", sa.Integer(), nullable=False),
        sa.Column("rows_imported", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("training_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("training_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("terms_url", sa.String(length=500), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "sports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "tax_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("jurisdiction", sa.String(length=80), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("tax_basis", sa.String(length=30), nullable=False),
        sa.Column("stake_tax_rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("winnings_tax_rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("payout_withholding_rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("commission_rate", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("fixed_fee", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_label", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("effective_to IS NULL OR effective_to > effective_from"),
        sa.CheckConstraint("fixed_fee >= 0"),
        sa.CheckConstraint(
            "stake_tax_rate >= 0 AND stake_tax_rate <= 1 "
            "AND winnings_tax_rate >= 0 AND winnings_tax_rate <= 1 "
            "AND payout_withholding_rate >= 0 AND payout_withholding_rate <= 1 "
            "AND commission_rate >= 0 AND commission_rate <= 1"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("train_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validation_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("test_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bookmaker_constraints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("minimum_stake", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("maximum_stake", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("stake_increment", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_label", sa.String(length=160), nullable=False),
        sa.CheckConstraint("maximum_stake IS NULL OR maximum_stake > 0"),
        sa.CheckConstraint("minimum_stake >= 0"),
        sa.CheckConstraint("stake_increment > 0"),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bookmaker_id", "currency", "observed_at"),
    )
    op.create_table(
        "bookmaker_tax_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.Integer(), nullable=False),
        sa.Column("tax_profile_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("valid_to IS NULL OR valid_to > valid_from"),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_profile_id"],
            ["tax_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bookmaker_id", "tax_profile_id", "valid_from"),
    )
    op.create_table(
        "coaches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_coach_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "provider_coach_key"),
    )
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=80), nullable=False),
        sa.Column("season", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sport_id", "name", "season"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_player_key", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("position", sa.String(length=40), nullable=False),
        sa.Column("preferred_side", sa.String(length=20), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "provider_player_key"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index("ix_players_name", ["name"], unique=False)

    op.create_table(
        "provider_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_ingestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("import_job_id", sa.Integer(), nullable=True),
        sa.Column("source_key", sa.String(length=255), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ingested_at >= observed_at"),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "source_key", "content_sha256"),
    )
    with op.batch_alter_table("raw_ingestions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_ingestions_observed_at"), ["observed_at"], unique=False
        )

    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sport_id", "name"),
    )
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("benchmark", sa.String(length=80), nullable=False),
        sa.Column("dimension", sa.String(length=60), nullable=False),
        sa.Column("dimension_value", sa.String(length=120), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["backtest_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "benchmark", "dimension", "dimension_value"),
    )
    op.create_table(
        "coach_tenures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("valid_to IS NULL OR valid_to > valid_from"),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coach_id", "team_id", "valid_from"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_event_key", sa.String(length=120), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.CheckConstraint("home_team_id <> away_team_id"),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "provider_event_key"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_kickoff_at"), ["kickoff_at"], unique=False)

    op.create_table(
        "player_registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("squad_number", sa.Integer(), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("valid_to IS NULL OR valid_to > valid_from"),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "team_id", "valid_from"),
    )
    op.create_table(
        "team_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("metric_schema_version", sa.String(length=60), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("matches", sa.Integer(), nullable=False),
        sa.Column("goals_for", sa.Float(), nullable=False),
        sa.Column("goals_against", sa.Float(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.CheckConstraint("matches >= 0"),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "competition_id", "provider_id", "metric_schema_version", "as_of"
        ),
    )
    op.create_table(
        "availability_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("evidence_class", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1"),
        sa.CheckConstraint("effective_to IS NULL OR effective_to > effective_from"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["availability_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("availability_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_availability_reports_observed_at"), ["observed_at"], unique=False
        )

    op.create_table(
        "bet_builder_quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("legs", sa.JSON(), nullable=False),
        sa.Column("joint_probability", sa.Float(), nullable=False),
        sa.Column("fair_odds", sa.Float(), nullable=False),
        sa.Column("offered_odds", sa.Float(), nullable=True),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lineup_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=True),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("lineup_type", sa.String(length=30), nullable=False),
        sa.Column("formation", sa.String(length=30), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1"),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "team_id", "lineup_type", "observed_at"),
    )
    with op.batch_alter_table("lineup_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lineup_snapshots_observed_at"), ["observed_at"], unique=False
        )

    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("market_type", sa.String(length=40), nullable=False),
        sa.Column("line", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("line_key", sa.String(length=20), nullable=False),
        sa.Column("period", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("settlement_rule_key", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "market_type", "line_key", "period", "currency", "settlement_rule_key"
        ),
    )
    op.create_table(
        "match_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("home_goals", sa.Integer(), nullable=False),
        sa.Column("away_goals", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["match_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "provider_id", "observed_at"),
    )
    op.create_table(
        "matchup_feature_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("feature_version", sa.String(length=60), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("sensitivity", sa.JSON(), nullable=False),
        sa.Column("missing_inputs", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "feature_version", "as_of"),
    )
    with op.batch_alter_table("matchup_feature_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_matchup_feature_snapshots_as_of"), ["as_of"], unique=False
        )

    op.create_table(
        "player_appearances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("starter", sa.Boolean(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(length=40), nullable=False),
        sa.Column("role", sa.String(length=80), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("minutes >= 0 AND minutes <= 130"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "player_id", "provider_id"),
    )
    op.create_table(
        "player_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("metric_schema_version", sa.String(length=60), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("minutes >= 0 AND minutes <= 130"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "player_id", "provider_id", "metric_schema_version"),
    )
    op.create_table(
        "tactical_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=True),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("formation", sa.String(length=30), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tactical_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tactical_snapshots_observed_at"), ["observed_at"], unique=False
        )

    op.create_table(
        "arbitrage_opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("inverse_sum", sa.Float(), nullable=False),
        sa.Column("total_cash_outlay", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("minimum_net_payout", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("net_profit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("net_roi", sa.Float(), nullable=False),
        sa.Column("tax_status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.CheckConstraint("inverse_sum > 0"),
        sa.CheckConstraint("total_cash_outlay > 0"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("arbitrage_opportunities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_arbitrage_opportunities_calculated_at"), ["calculated_at"], unique=False
        )

    op.create_table(
        "lineup_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lineup_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("starter", sa.Boolean(), nullable=False),
        sa.Column("position", sa.String(length=40), nullable=False),
        sa.Column("role", sa.String(length=80), nullable=True),
        sa.Column("expected_probability", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "expected_probability IS NULL OR "
            "(expected_probability >= 0 AND expected_probability <= 1)"
        ),
        sa.ForeignKeyConstraint(
            ["lineup_snapshot_id"], ["lineup_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lineup_snapshot_id", "player_id"),
    )
    op.create_table(
        "model_event_outputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("lineup_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("matchup_feature_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inputs_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_class", sa.String(length=30), nullable=False),
        sa.Column("home_lambda", sa.Float(), nullable=False),
        sa.Column("away_lambda", sa.Float(), nullable=False),
        sa.Column("score_matrix", sa.JSON(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lineup_snapshot_id"],
            ["lineup_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matchup_feature_snapshot_id"],
            ["matchup_feature_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "model_version_id", "predicted_at"),
    )
    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("import_job_id", sa.Integer(), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_closing", sa.Boolean(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("source_label", sa.String(length=160), nullable=False),
        sa.CheckConstraint("ingested_at >= observed_at"),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
        ),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "bookmaker_id", "provider_id", "observed_at"),
    )
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_odds_snapshots_observed_at"), ["observed_at"], unique=False
        )

    op.create_table(
        "selections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "code"),
    )
    op.create_table(
        "arbitrage_legs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.Integer(), nullable=False),
        sa.Column("odds_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("tax_profile_id", sa.Integer(), nullable=True),
        sa.Column("decimal_odds", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("stake", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("gross_payout", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("taxes_and_fees", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("net_payout", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.CheckConstraint("decimal_odds > 1"),
        sa.CheckConstraint("stake > 0"),
        sa.CheckConstraint("taxes_and_fees >= 0"),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["odds_snapshot_id"],
            ["odds_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["arbitrage_opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["selections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_profile_id"],
            ["tax_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "selection_id"),
    )
    op.create_table(
        "model_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("output_id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("lower_probability", sa.Float(), nullable=False),
        sa.Column("upper_probability", sa.Float(), nullable=False),
        sa.Column("fair_odds", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["output_id"], ["model_event_outputs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["selections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("output_id", "selection_id"),
    )
    op.create_table(
        "odds_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("decimal_odds", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.CheckConstraint("decimal_odds > 1"),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["selections.id"],
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["odds_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "selection_id"),
    )
    op.create_table(
        "backtest_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("odds_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settlement", sa.String(length=20), nullable=True),
        sa.Column("stake", sa.Float(), nullable=False),
        sa.Column("profit_units", sa.Float(), nullable=True),
        sa.Column("closing_line_value", sa.Float(), nullable=True),
        sa.CheckConstraint("stake >= 0"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["odds_snapshot_id"],
            ["odds_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["model_predictions.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["backtest_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["selections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "event_id", "selection_id", "predicted_at"),
    )
    op.create_table(
        "value_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.Integer(), nullable=False),
        sa.Column("odds_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("signal_type", sa.String(length=40), nullable=False),
        sa.Column("offered_odds", sa.Float(), nullable=False),
        sa.Column("raw_implied_probability", sa.Float(), nullable=False),
        sa.Column("market_fair_probability", sa.Float(), nullable=False),
        sa.Column("model_probability", sa.Float(), nullable=False),
        sa.Column("expected_value", sa.Float(), nullable=False),
        sa.Column("probability_edge", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["odds_snapshot_id"],
            ["odds_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["model_predictions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["selections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("value_signals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_value_signals_generated_at"), ["generated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("value_signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_value_signals_generated_at"))

    op.drop_table("value_signals")
    op.drop_table("backtest_observations")
    op.drop_table("odds_prices")
    op.drop_table("model_predictions")
    op.drop_table("arbitrage_legs")
    op.drop_table("selections")
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_odds_snapshots_observed_at"))

    op.drop_table("odds_snapshots")
    op.drop_table("model_event_outputs")
    op.drop_table("lineup_members")
    with op.batch_alter_table("arbitrage_opportunities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_arbitrage_opportunities_calculated_at"))

    op.drop_table("arbitrage_opportunities")
    with op.batch_alter_table("tactical_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tactical_snapshots_observed_at"))

    op.drop_table("tactical_snapshots")
    op.drop_table("player_statistics")
    op.drop_table("player_appearances")
    with op.batch_alter_table("matchup_feature_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_matchup_feature_snapshots_as_of"))

    op.drop_table("matchup_feature_snapshots")
    op.drop_table("match_results")
    op.drop_table("markets")
    with op.batch_alter_table("lineup_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lineup_snapshots_observed_at"))

    op.drop_table("lineup_snapshots")
    op.drop_table("bet_builder_quotes")
    with op.batch_alter_table("availability_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_availability_reports_observed_at"))

    op.drop_table("availability_reports")
    op.drop_table("team_statistics")
    op.drop_table("player_registrations")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_kickoff_at"))

    op.drop_table("events")
    op.drop_table("coach_tenures")
    op.drop_table("backtest_results")
    op.drop_table("teams")
    with op.batch_alter_table("raw_ingestions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_ingestions_observed_at"))

    op.drop_table("raw_ingestions")
    op.drop_table("provider_jobs")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index("ix_players_name")

    op.drop_table("players")
    op.drop_table("competitions")
    op.drop_table("coaches")
    op.drop_table("bookmaker_tax_profiles")
    op.drop_table("bookmaker_constraints")
    op.drop_table("backtest_runs")
    op.drop_table("tax_profiles")
    op.drop_table("sports")
    op.drop_table("providers")
    op.drop_table("model_versions")
    op.drop_table("import_jobs")
    op.drop_table("bookmakers")
    # ### end Alembic commands ###
